# Generated by Django 3.1.1 on 2020-09-09 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.URLField(default='https://image.ibb.co/jw55Ex/def_face.jpg'),
        ),
    ]
