# Generated by Django 3.1.1 on 2020-09-10 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.URLField(default='https://image.ibb.co/jw55Ex/def_face.jpg'),
        ),
    ]
